### ISSUE TITLE
[BUG] MAP-4.5.2_ETH_FH5GL fails with MSG: The power diff is less than 5dBm

### ISSUE THREAD

**Issue by Mila-Sh** [prplfoundation/prplMesh#995] opened 2020-03-22 22:06 UTC
job: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/480661759

logs: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/480661759/artifacts/browse/logs/FAIL/MAP-4.5.2_ETH_FH5GL/

**Comment by rmelotte** [comment] 2020-03-23 08:54
This one is a duplicate of https://github.com/prplfoundation/prplMesh/issues/962

**Closed as completed by rmelotte** 2020-03-23 08:54 UTC
Labels: bug, certification
