### ISSUE TITLE
ugw_structs.h not available

### ISSUE THREAD

**Issue by chaitanya-dandamudi** [prplfoundation/prplMesh#493] opened 2019-11-20 12:51 UTC
Hi,

I am trying to build prplMesh with "ugw" target for ARM architecture with cross-compilation. While buidling prplMesh/framework directory seeing following error:

prplmesh_root/prplMesh/framework/platform/bpl/ugw/cfg/cal/cal_interface.h:13:25: fatal error: ugw_structs.h: No such file or directory

This file is not available in prplMesh directory. Can you please check and let me know how to access this file.

**Comment by tomereli** [comment] 2019-11-20 15:31
UGW BPL in prplMesh is not supported anymore.
@vitalybu is now working on bringing up prplMesh on UGW8.x which is completely different and uses UCI instead of CAL interface.

*prplMesh will not support for older UGW versions* - therefore considering as not a bug and closing.

**Closed as completed by tomereli** 2019-11-20 15:31 UTC
Labels: bug
